rosbag2_performance_benchmarking_node:
  ros__parameters:
    publishers: # publisher_groups parameter needs to include all the subsequent groups 
      publisher_groups: [ "many_frequent_small" ]
      wait_for_subscriptions: True
      many_frequent_small:
        publishers_count:   10
        topic_root:         "benchmarking_small"
        msg_size_bytes:     10000
        msg_count_each:     500
        rate_hz:            100
        qos:  # qos settings are ignored for writer only benchmarking
          qos_depth:          5000
          qos_reliability:    "reliable" # "best_effort" # "reliable"
          qos_durability:     "volatile" # "transient_local"
